---
- name: Read-write git checkout from github
  ansible.builtin.git:
    repo: "{{ item.value }}"
    dest: $HOME/GITHUB/"{{ item.key }}"
    key_file: $HOME/.ssh/id_ed25519
    accept_hostkey: true